### ISSUE TITLE
disease_data.json doesn't exist 

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/dsc-2-14-10-exploring-json-schemas-lab#1]
Load the data from the file disease_data.json

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-1-e099c235a282> in <module>
>       2 import json
>       3 
> ----> 4 f = open('disease_data.json', 'r')
>       5 data = json.load(f)
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'disease_data.json'

**Comment by LoreDirick** [comment]
Thanks for creating this issue, it turned out the `.json`-file had the wrong name. Fixed now and changed `2016_csc_data.json` to `disease_data.json`
